### ISSUE TITLE
MCPE

### ISSUE THREAD

**Issue by TheDiamondYT1** [HAZARDU5/minecraft-realms-map#1]
Im trying to do this for MCPE 

https://gist.github.com/TheDiamondYT1/bc41b69464426a1693e8219bac5d34a5

**Comment by UXVirtual** [comment]
The map generation script currently doesn't support Minecraft Pocket Edition. I might add support for this in the future.

**Comment by TheDiamondYT1** [comment]
I think you first have to authenticate with xbox live servers.
